import os


class DocumentationAgent:

    def __init__(self):

        self.name = "Documentation Agent"

    def run(self, memory):

        print("Generating documentation...")

        report = self.generate_report(
            memory
        )

        self.save_report(
            report
        )

        memory.update(
            "documentation_report",
            report
        )

        print("Documentation completed")

    def generate_report(
        self,
        memory
    ):

        repo_path = memory.get(
            "repo_path"
        )

        language = memory.get(
            "language"
        )

        files = memory.get(
            "files"
        ) or []

        review_report = memory.get(
            "review_report"
        ) or "Not Available"

        test_report = memory.get(
            "test_report"
        ) or "Not Available"

        lines = []

        lines.append(
            "# AutoDevAI Documentation Report"
        )

        lines.append("")

        lines.append(
            "## Repository"
        )

        lines.append(
            str(repo_path)
        )

        lines.append("")

        lines.append(
            "## Programming Language"
        )

        lines.append(
            str(language)
        )

        lines.append("")

        lines.append(
            "## Total Files"
        )

        lines.append(
            str(len(files))
        )

        lines.append("")

        lines.append(
            "## Project Files"
        )

        for file in files:

            lines.append(
                f"- {file}"
            )

        lines.append("")

        lines.append(
            "## Code Review Summary"
        )

        lines.append(
            review_report
        )

        lines.append("")

        lines.append(
            "## Testing Summary"
        )

        lines.append(
            test_report
        )

        lines.append("")

        lines.append(
            "Report generated by AutoDevAI."
        )

        return "\n".join(
            lines
        )

    def save_report(
        self,
        report
    ):

        os.makedirs(
            "reports",
            exist_ok=True
        )

        report_path = os.path.join(
            "reports",
            "documentation_report.md"
        )

        with open(
            report_path,
            "w",
            encoding="utf-8"
        ) as file:

            file.write(
                report
            )