import os

from core.score_engine import ScoreEngine
from storage.models import save_scan


class FinalReportAgent:

    def __init__(self):

        self.name = "Final Report Agent"

    def run(self, memory):

        print("Generating final report...")

        report = self.generate_report(
            memory
        )

        scores = ScoreEngine().calculate(
            memory
        )

        scan = {

            "repository": memory.get(
                "repo_path"
            ),

            "language": memory.get(
                "language"
            ),

            "files": len(
                memory.get(
                    "files"
                ) or []
            ),

            "score": scores[
                "overall"
            ],

            "security": scores[
                "security"
            ],

            "testing": scores[
                "testing"
            ],

            "documentation": scores[
                "documentation"
            ]

        }

        save_scan(
            scan
        )

        self.save_report(
            report
        )

        memory.update(
            "final_report",
            report
        )

        print(
            "Final report generated"
        )

    def generate_report(
        self,
        memory
    ):

        repo_path = memory.get(
            "repo_path"
        )

        language = memory.get(
            "language"
        )

        files = memory.get(
            "files"
        ) or []

        review = memory.get(
            "review_report"
        ) or "Not Available"

        testing = memory.get(
            "test_report"
        ) or "Not Available"

        documentation = memory.get(
            "documentation_report"
        ) or "Not Available"

        security = memory.get(
            "security_report"
        ) or "Not Available"

        lines = []

        lines.append(
            "# AutoDevAI Final Report"
        )

        lines.append("")

        lines.append(
            "========================================"
        )

        lines.append("")

        lines.append(
            f"Repository : {repo_path}"
        )

        lines.append(
            f"Language   : {language}"
        )

        lines.append(
            f"Total Files: {len(files)}"
        )

        lines.append("")

        lines.append(
            "========================================"
        )

        lines.append("")

        lines.append(
            "## Code Review"
        )

        lines.append("")

        lines.append(
            review
        )

        lines.append("")

        lines.append(
            "========================================"
        )

        lines.append("")

        lines.append(
            "## Testing"
        )

        lines.append("")

        lines.append(
            testing
        )

        lines.append("")

        lines.append(
            "========================================"
        )

        lines.append("")

        lines.append(
            "## Documentation"
        )

        lines.append("")

        lines.append(
            documentation
        )

        lines.append("")

        lines.append(
            "========================================"
        )

        lines.append("")

        lines.append(
            "## Security"
        )

        lines.append("")

        lines.append(
            security
        )

        lines.append("")

        lines.append(
            "========================================"
        )

        lines.append("")

        lines.append(
            "Generated by AutoDevAI"
        )

        return "\n".join(
            lines
        )

    def save_report(
        self,
        report
    ):

        os.makedirs(
            "reports",
            exist_ok=True
        )

        report_path = os.path.join(
            "reports",
            "final_report.md"
        )

        with open(
            report_path,
            "w",
            encoding="utf-8"
        ) as file:

            file.write(
                report
            )